### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by vt107** [TobyG74/twitter-downloader#1]
I got error Error: connect ECONNREFUSED 127.0.0.1:443 when trying the sample code. Maybe because pastebin.com is not working anymore...

**Comment by TobyG74** [comment]
Still working on me and other users, maybe the API is blocking requests from your country

**Comment by TobyG74** [comment]
Hi, sorry for the late response. please try again the module, because I've updated it
